# Generated by Django 4.1.5 on 2023-02-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_ref',
            field=models.CharField(default='AAAAAAAAAAA', max_length=15),
            preserve_default=False,
        ),
    ]
