# Generated by Django 4.1.5 on 2023-02-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_payment_ref_order_paystack_payment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paystack_payment_ref',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
